  services:
    monitor:
      image: ${SOLACE_DOCKER_IMAGE}
      container_name: ${BROKER_NAME}
      user: ${SOLACE_USER_ID}
      shm_size: ${SHM_SIZE}
      deploy:
        restart_policy:
          condition: on-failure
          max_attempts: 1
      ulimits:
        nofile:
          soft: 2448
          hard: 6592
        core: -1    
      ports:
        - "1943:1943" # SEMP API
        - "8300:8300"   # HA sync
        - "8301:8301"   # HA sync
        - "8302:8302"   # HA sync
        - "8301:8301/udp"
        - "8302:8302/udp"
      environment:
        - username_admin_globalaccesslevel=${USERNAME_ADMIN_GLOBALACCESSLEVEL}
        - username_admin_passwordfilepath=${USERNAME_ADMIN_PASSWORD_FILE_NAME}
        - username_dynatrace-view_globalaccesslevel=${USERNAME_DYNATRACE_GLOBALACCESSLEVEL}
        - username_dynatrace-view_passwordfilepath=${USERNAME_DYNATRACE_PASSWORD_FILE_NAME}
        - redundancy_enable=yes
        - redundancy_authentication_presharedkey_key=YmFuY29kZWNoaWxlcHJlcHJvZHFhbGxhdmVrZXlzb2xhY2VzdXBlcnNlY3JldDAx
        - redundancy_group_node_prdprimary_connectvia=lsclprocicmsolace01
        - redundancy_group_node_prdprimary_nodetype=message_routing
        - redundancy_group_node_prdbackup_connectvia=lsclprocicmsolace02
        - redundancy_group_node_prdbackup_nodetype=message_routing
        - redundancy_group_node_prdmonitoring_connectvia=lsclprocicmsolace03
        - redundancy_group_node_prdmonitoring_nodetype=monitoring
        - nodetype=monitoring
        - routername=${ROUTER_NAME}
        - TZ=America/Santiago
        - tls_servercertificate_filepath=${CERTIFICATE}
      volumes:
        - /solace/data:/var/lib/solace:Z
        - /solace/secrets:/run/secrets